### ISSUE TITLE
Showing Application Error when pressing Analyse

### ISSUE THREAD

**Issue by josho495** [bmacho/bughouse-viewer#11]
![Capture](https://user-images.githubusercontent.com/94729672/205333323-89cfcb03-68a1-4d3b-9188-247fd7d4c6f2.JPG)

**Comment by bmacho** [comment]
Thank you for your report!

Heroku discontinued its free plan. I'm looking for options to host the analyzer elsewhere. I removed the analysis buttons for now.

**Comment by josho495** [comment]
Any timeline for a new host? Would you consider a monthly donation from chess.com users for example?

**Comment by bmacho** [comment]
I've put it on https://render.com , it is working for me now.

Not really, no.
