### ISSUE TITLE
Game not loading

### ISSUE THREAD

**Issue by antoyo** [bmacho/bughouse-viewer#12]
Hi.
When I paste a chess.com URL, the game doesn't load.
The browser console shows this error:
```
TypeError: undefined is not an object (evaluating 'gameB.game.moveList')
```
Thanks to fix this issue.

**Comment by bmacho** [comment]
It is indeed broken, [they've changed their internals](https://www.chess.com/clubs/forum/view/put-back-the-other-game-id-in-to-the-callback-live-game-gameid-response-for-bughouse), the callback reply doesn't include the partner game id anymore. I'll put on an under construction sign for now, and look into it later.

**Comment by bmacho** [comment]
It should be better now. As chess.com currently doesn't provide exact information about the other game, it can't be perfect as it was before :|

**Comment by antoyo** [comment]
Thanks. It works well!
