### ISSUE TITLE
Game not loading

### ISSUE THREAD

**Issue by josho495** [bmacho/bughouse-viewer#4]
When I copy the chess.com link and paste it after game_id= , nothing happens. I tried Opera, Chrome, Edge and Brave. Tried different chess.com URLs also.
It shows the initial board setup and that is all.

Thanks.

**Comment by josho495** [comment]
Resolved now. Thanks.

**Comment by bmacho** [comment]
Thank you for your bug report, I got an email for it! 

I changed the proxy from https://allorigins.win/ (which is up again, yay) to a cloudflare workers proxy, it should handle 100 000 requests a day (1 game view needs 2 requests)

---

The proxy is running under my account, but it does not provide me any data of its usage (besides a total usage counter), no ip addresses, countries, individual viewers or such (nor does github pages for that matter).
