### ISSUE TITLE
Multiple lines

### ISSUE THREAD

**Issue by josho495** [bmacho/bughouse-viewer#7]
This project is awesome. Many thanks to you!

I notice the engine only gives 1 line when evaluating (best line)
Is it possible to give multiple lines? ie Best 3 moves rather than the 1 line? Could that be an option?

Thanks
Josh,

**Comment by bmacho** [comment]
It is not really possible to modify the current analysis board, it is buggy, untouchable and fragile. I don't recommend anyone to try and modify it. Also it is compiled to js, and I don't think that the environment that produced it can be restored.

However there is already an online multi line bughouse "analyzer" : https://fairy-stockfish-nnue-wasm.vercel.app/analysis.html ( the multiPV field means the number of lines ) it is text based, but one can try and tie it together with a chessboard. 

Probably I will sometime, but anyone else could do it.
